s5e8825-common: Allow duplicate sysprops
Thank you crDroid for making my life miserable.

error: found duplicate sysprop assignments:
ro.config.ringtone=Orion.ogg
ro.config.ringtone=Your_new_adventure.ogg
error: found duplicate sysprop assignments:
ro.config.alarm_alert=Hassium.ogg
ro.config.alarm_alert=Fresh_start.ogg
error: found duplicate sysprop assignments:
ro.config.notification_sound=Argon.ogg
ro.config.notification_sound=Eureka.ogg
error: found duplicate sysprop assignments:
setupwizard.theme=glif_v4
setupwizard.theme=glif_v3_light
setupwizard.theme=glif_v4_light
00:27:33 ninja failed with: exit status 1

failed to build some targets (03:06 (mm:ss)) ####

In reality, the reason this happens is because my vendor/google/*
repos set some props that are already set by crDroid without using ?=,
so they cannot be overriden.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>